### ISSUE TITLE
Subframe auslesen Problem...

### ISSUE THREAD

**Issue by sgu98** [th-koeln-optec-messsysteme/Vaisala_RS41_TU_Analysis#1]
Laut den Dokumenten ist z.B. die Subframe Nummer in Byte 18 im Status-Block des Frames. Der Status Block beginnt ab Byte 0x3B.
Die Subframe Nummer sollte also bei 0x4C liegen, aber die Werte passen nicht. Was übersehen wir hier? @bazjo

**Comment by bazjo** [comment]
`0x3B + 0x17 = 0x52`

immer hexadezimal bleiben, und der subframe counter ist die `0x17`, nicht die `0x18`

[hier](https://github.com/bazjo/RS41_Decoding/tree/master/RS41-SGP) wird das aber auch noch etwas anschaulicher, wenn man schaut, wo der fragliche beispielwert `0x20` im Frame vorkommt
