### ISSUE TITLE
Leicht negative Werte für die Luftfeuchtigkeit

### ISSUE THREAD

**Issue by sgu98** [th-koeln-optec-messsysteme/Vaisala_RS41_TU_Analysis#2]
Hallo @bazjo ,
wir haben versucht, die CRC Prüfung für die einzelnen Frames zu integrieren, aber es funktioniert noch nicht. Du meintest, wir sollen nur die Adressen in den zwei Zeilen anpassen. Das haben wir gemacht, jetzt passt keine CRC Nummer mehr...
Außerdem kriegen wir für die Luftfeuchte Werte knapp unter 0, zB. -2% in größeren Höhen. Hast du eine Idee, woran das liegen könnte? Der Graph ist auf der Hauptseite des Repositorys. 
Vielen Dank für die Hilfe :-)

**Comment by bazjo** [comment]
Ein Issue pro Problem (steht auch im Namen) ;D

Versucht das Beispiel nachzuvollziehen, und zu verstehen, was ihr verändern müsst. Dann debuggt euren Code Stück für Stück

Mit den geflogenen Altsonden, die schon mal vorher gflogen sind, hatten wir ein Problem bei den Feuchtigkeitswerten gegenüber unserem Referenzhygrometer in Form einer arbiträren Abweichung. Am besten achtet ihr da hauptsächlich auf das Delta zwischen den beiden Sonden, und eurer Auswertung und der vom RS41 Tracker.

Interessant ist auch, ob das Delta mit anderen Parametern korreliert, oder ob man die Abweichung der Altsonden durch eine Kalibration mit einem Referenzhygrometer weg bekommt. Wenn euch die genauen Abweichungen der geflogenen Sonden mit unserem Hygrometer interessieren, muss ich nächste Woche in der TH nach den genauen Werten schauen
